cabal-version:      3.0
name:               asflp
version:            0.1.0.0
-- A short (one-line) description of the package.
-- synopsis:
-- A longer description of the package.
-- description:
license:            MIT
license-file:       LICENSE
author:             drwadu
maintainer:         alamzan94@live.de
build-type:         Simple
extra-doc-files:    CHANGELOG.md
common warnings
    ghc-options: -Wall
library
    exposed-modules:  
      Lib
      Lnn.Solver 
      Lnn.Parser 
      Lnn.Compiler 
      Lnn.Logic 
      Lnn.Neuro 

    -- Modules included in this library but not exported.
    other-modules: 
      Fuzzy 
      Neuron 
      Inference 
      Utils 
      Parser 
      --Infer 
    --, Interface

    -- LANGUAGE extensions used by modules in this package.
    -- other-extensions:
    build-depends:    base, containers
    hs-source-dirs:   src
    default-language: Haskell2010

--foreign-library hsasflp
--  type: native-shared
--  other-modules: Lib, Fuzzy, Neuron, Inference, Utils, Parser, Interface
--  build-depends:    base, containers
--  hs-source-dirs:   src
--  default-language: Haskell2010

executable asflp
    import:           warnings

    -- .hs or .lhs file containing the Main module.
    main-is:          Main.hs

    -- Modules included in this executable, other than Main.
    other-modules: 
      Lib 
      Fuzzy 
      Neuron 
      Inference 
      Utils 
      Parser 
      Lnn.Solver 
      Lnn.Parser 
      Lnn.Compiler 
      Lnn.Logic 
      Lnn.Neuro 
      --Infer
    --, Interface,

    -- LANGUAGE extensions used by modules in this package.
    -- other-extensions:

    -- Other library packages from which modules are imported.
    build-depends:    base, containers

    -- Directories containing source files.
    hs-source-dirs:   app, src

    -- Base language which the package is written in.
    default-language: Haskell2010

test-suite test
    type: exitcode-stdio-1.0
    ghc-options: -Wall
    hs-source-dirs: test
    main-is:    Tests.hs
    other-modules: Lnn
     --H1 
     --H2 
     --ImmediateConsequenceOperator 
    build-depends: base, HUnit, asflp, containers, random
    default-language: Haskell2010

--test-suite experiments
--    type: exitcode-stdio-1.0
--    ghc-options: -Wall
--    hs-source-dirs: experiments
--    main-is:    Experiments.hs
--    other-modules:  H1, Ico, Lib
--    build-depends: base, HUnit, asflp, containers, QuickCheck, checkers, random
--    default-language: Haskell2010
