cabal-version:      3.0
name:               asflp
version:            0.1.0.0
synopsis:
description:
license:            MIT
license-file:       LICENSE
author:             drwadu
maintainer:         alamzan94@live.de
build-type:         Simple
extra-doc-files:    CHANGELOG.md
common warnings
    ghc-options: -Wall
library
    exposed-modules:  
      Lnn.Solver 
      Lnn.Parser 
      Lnn.Compiler 
      Lnn.Logic 
      Lnn.Neuro 
      Ico.Solver 
      Ico.Parser 
    other-modules: 
      Utils 
      -- Interface
    build-depends:    base, containers
    hs-source-dirs:   src
    default-language: Haskell2010

--foreign-library hsasflp
--  type: native-shared
--  other-modules: Lib, Fuzzy, Neuron, Inference, Utils, Parser, Interface
--  build-depends:    base, containers
--  hs-source-dirs:   src
--  default-language: Haskell2010

executable asflp
    import:           warnings
    main-is:          Main.hs
    other-modules: 
      Utils 
      Lnn.Solver 
      Lnn.Parser 
      Lnn.Compiler 
      Lnn.Logic 
      Lnn.Neuro 
      Ico.Solver 
      Ico.Parser 
      --Interface
    build-depends:    base, containers
    hs-source-dirs:   app, src
    default-language: Haskell2010

test-suite test
    type: exitcode-stdio-1.0
    ghc-options: -Wall
    hs-source-dirs: test
    main-is:    Tests.hs
    other-modules: Lnn
     --H1 
     --H2 
     --ImmediateConsequenceOperator 
    build-depends: base, HUnit, asflp, containers, random
    default-language: Haskell2010

--test-suite experiments
--    type: exitcode-stdio-1.0
--    ghc-options: -Wall
--    hs-source-dirs: experiments
--    main-is:    Experiments.hs
--    other-modules:  H1, Ico, Lib
--    build-depends: base, HUnit, asflp, containers, QuickCheck, checkers, random
--    default-language: Haskell2010
